### ISSUE TITLE
No html inline css syntax highlighting - build 3114

### ISSUE THREAD

**Issue by lspoor** [SublimeText/Spacegray#182]
Have just moved over to ST3 and straight back in with Spacegrey (used with ST2 fine) but it appears there is no styling on inline CSS within HTML files.

![screen shot 2016-05-17 at 09 25 38](https://cloud.githubusercontent.com/assets/1685176/15315755/69c8f3ce-1c11-11e6-8e00-f4209ec056d7.png)

**Comment by marcofugaro** [comment]
It is indeed syntax-highlighted, it takes the colours directly from the css:
![](http://i.imgur.com/8y7NwdU.png)


The real problem is that in css the property name and vales have the same colour, an enhancement would be to color the property differently, for example:
![](http://i.imgur.com/ZbSh3zh.png)
